---

- name: Validate mandatory parameter present
  fail:
    msg: "The f5app_services_package_destination parameter is not defined."
  when:
    - f5app_services_package_destination is not defined

- name: Validate mustually exclusive parameters are not present
  fail:
    msg: "The 'f5app_services_package_checksum_url' and 'f5app_services_package_checksum ' parameters cannot be specified together."
  when:
    - f5app_services_package_checksum_url is defined and f5app_services_package_checksum is defined

- name: Download an RPM package to controller, no checksum validation
  get_url:
    url: "{{ f5app_services_package_url }}"
    dest: "{{ f5app_services_package_destination }}"
    validate_certs: false
  when:
    - f5app_services_package_checksum_url is not defined and f5app_services_package_checksum is not defined

- name: Download an RPM package to controller, checksum validation from url
  get_url:
    url: "{{ f5app_services_package_url }}"
    dest: "{{ f5app_services_package_destination }}"
    checksum: "sha256:{{ f5app_services_package_checksum_url }}"
    validate_certs: false
  when:
    - f5app_services_package_checksum_url is defined

- name: Download an RPM package to controller, checksum validation from variable
  get_url:
    url: "{{ f5app_services_package_url }}"
    dest: "{{ f5app_services_package_destination }}"
    checksum: "sha256:{{ f5app_services_package_checksum }}"
    validate_certs: false
  when:
    - f5app_services_package_checksum is defined

- name: Check the RPM file is downloaded and present
  stat:
    path: "{{ f5app_services_package_destination }}"
  register: rpmstatus
  until: rpmstatus.stat.exists
  retries: 10
  delay: 15

- name: Set the package file path fact if file is downloaded
  set_fact:
    f5app_services_package_path: "{{ f5app_services_package_destination }}"


- import_tasks: install.yaml
  when: f5app_services_package_path is defined
